#!/bin/sh

case "$1" in
  start)
    printf "Starting rndis: "
    insmod /mnt/system/ko/dwc2.ko
    /etc/uhubon.sh device
    /etc/run_usb.sh probe rndis
    /etc/run_usb.sh start
    ifconfig usb0 up
    busybox-full zcip usb0 /usr/libexec/zcip.script
    cp -fv /etc/examples/udhcpd.usb0.conf /tmp/udhcpd.usb0.conf
    id=$(hostname | tail -c 5)
    idh=$(printf "%d" $(echo "$id" | head -c 2))
    idl=$(printf "%d" $(echo "$id" | tail -c 3))
    if [ "$idh" -eq 0 ]
    then
        idh="254"
    fi
    if [ "$idl" -eq 0 ]
    then
        idl="254"
    fi
    if [ $idh -ge 254 ]
    then
        export idh="254"
    fi
    if [ $idl -ge 254 ]
    then
        export idl="254"
    fi
    sed -i -e "s/10.0.0/10.$idh.$idl/g" /tmp/udhcpd.usb0.conf
    ip addr add 10.$idh.$idl.1/24 dev usb0
    busybox-full udhcpd -S -I 10.$idh.$idl.1 /tmp/udhcpd.usb0.conf
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    printf "Stopping rndis: "
    echo "OK"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
