#!/bin/sh

hex2mac() {
        MAC=""
        seq 2 2 12 | while read i
        do
                echo -n ${1} | head -c $i | tail -c 2
                if [ $i != 12 ]
                then
                        echo -n ':'
                fi
        done | tr '[:upper:]' '[:lower:]'
}


name="licheervnanobad0"
ethmac="$(cat /sys/class/net/eth0/address)"

if [ -e /sys/class/cvi-base ]
then
	name="licheervnano$(cat /sys/class/cvi-base/base_uid | tr -d ':' | tail -c 5)"
	ethmac="$(hex2mac 48da356f$(cat /sys/class/cvi-base/base_uid | tr -d '_' | tail -c 5))"
fi


if [ -e /sys/class/net/wlan0/address ]
then
	name="licheervnano$(cat /sys/class/net/wlan0/address | tr -d ':' | tail -c 5)"
fi

hostname $name
ifconfig eth0 down
ip link set eth0 address ${ethmac}
ifconfig eth0 up
